# Generated by Django 3.2.3 on 2021-05-17 21:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20210517_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='tiny',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
