# Generated by Django 3.2.3 on 2021-05-17 21:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_tiny'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='tiny',
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(verbose_name='Подробное описание'),
        ),
    ]
