# Generated by Django 3.2.3 on 2021-05-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_photo_upload_dir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='upload_dir',
        ),
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.CharField(max_length=500, verbose_name='Короткое описание'),
        ),
    ]
