# Generated by Django 3.2.3 on 2021-05-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20210528_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.CharField(default=None, editable=False, max_length=100, null=True),
        ),
    ]
