# Generated by Django 3.2.3 on 2021-06-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='ordering_position',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(verbose_name='Короткое описание'),
        ),
    ]
