# Generated by Django 3.2.3 on 2021-06-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20210603_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.CharField(blank=True, default=None, editable=False, max_length=100, null=True, unique=True),
        ),
    ]
