# Generated by Django 3.2.3 on 2021-06-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_auto_20210626_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.CharField(blank=True, default='', editable=False, max_length=100, unique=True),
        ),
    ]
