# Generated by Django 3.2.3 on 2022-04-12 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_place_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='slug',
            new_name='private_field_to_store_upload_dir_name',
        ),
    ]
