# Generated by Django 3.2.3 on 2022-04-23 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_rename_slug_place__upload_dir'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('title', 'coordinates')},
        ),
    ]
